version: '3.8'

services:
  server:
    build:
      context: ./server
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb+srv://db-admin:lFyEp0kHQqdHvbLk@project0925-cluster.zwsluo4.mongodb.net/?retryWrites=true&w=majority&appName=Project0925-Cluster
    depends_on: 
      - mongo

  client:
    build:
      context: ./client
    ports:
      - "3000:80"

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
